### ISSUE TITLE
C360 Not Opening for me

### ISSUE THREAD

**Issue by Busolini** [CallumCarmicheal/c360-IssueTracker#10]
When I go to log in, I enter my stuff, it logs me in, and then I get  the message in the bottom right when it says "Welcome back" but shortly after the app stops loading and I get a "Chaotic360 stopped working". I'm up to date on my framework and everything but nothing is working.

**Comment by rBc6mzwpTd745Kh** [comment]
I'm having this problem, too. It's been at least a month and I've tried contacting the Chaotic360 team, but nothing has surfaced from this effort.

**Comment by CallumCarmicheal** [comment]
Hello @Busolini @rBc6mzwpTd745Kh i have not been on github or my skype account in around a week due to real life complication, i am here now and if you are still receiving these issues (most likely due to a issue of me being away unable to maintain the server system), please contact my skype: callum_carmicheal. 

Ill be happy to resolve your issue as fast as possible.

@Busolini 
@rBc6mzwpTd745Kh
