### ISSUE TITLE
Chaotic360 and windows 10

### ISSUE THREAD

**Issue by Fkinning** [CallumCarmicheal/c360-IssueTracker#12]
is there any known problems with chaotic 64bit windows 10 

all drivers are up to date  all windows are up to date on framework 4.7 up to date 
any advice would be grateful

**Comment by CallumCarmicheal** [comment]
What is your issue could you explain more? I am unaware what you mean by any issues?

**Comment by Fkinning** [comment]
it will not load up

**Comment by CallumCarmicheal** [comment]
Could you talk to me on the c360 discord chat. I may need you to share screens.

**Comment by Fkinning** [comment]
yes you can message me

**Comment by CallumCarmicheal** [comment]
@Fkinning what is your discord?

**Comment by Fkinning** [comment]
I DONT KNOW DO YOU HAVE SOME THING I CAN HIT YOU UP ON

**Comment by CallumCarmicheal** [comment]
@Fkinning https://discord.gg/eSQFx9q Im always on discord, it will be hard to contact me on any other platform because i don't check my emails that often and i'm almost never on skype anymore because it's broken on my pc.

Once you sign up / join Discord goto the #support channel located in the left side and then type "@Callum Carmicheal#5792" To message me. It will be the easiest way to contact me.
