### ISSUE TITLE
wrong machine id?

### ISSUE THREAD

**Issue by grizzlydean** [CallumCarmicheal/c360-IssueTracker#9]
i copy and pasted my machine id and now wont let me sign in...

**Comment by CallumCarmicheal** [comment]
I have been made aware of this issue and i am currently working on a fix for this, i am sorry for any inconveniences this has caused. I am unable to handle any support requires although there are other staff members that will be able to comply with such requests - If you have not solved your problem yet please contact of those staff members to get your Machine ID changed. This issue is only temporary and should be fixed in a update or 2.
